var P8CONFIG = {
		url: 'http://www.zsxlzx.net',
		RESOURCE: '',
		language: 'zh-cn',
		controller: '/index.php',
		U_controller: '/u.php',
		cookie_prefix: 'yc2f6s_',
		cookie_path: '/',
		base_domain: 'zsxlzx.net',
		mobile_status: 0,
		mobile_auto_jump: 1,
		mobile_url: 'http://www.zsxlzx.net',
		
	URI: {
		'cms': {'': {url: '/cms',controller: '/index.php/cms',U_controller: '/u.php/cms'},
			'category': {url: '/cms/modules/category',controller: '/index.php/cms/category',U_controller: '/u.php/cms/category'},
			'item': {url: '/cms/modules/item',controller: '/index.php/cms/item',U_controller: '/u.php/cms/item'},
			'model': {url: '/cms/modules/model',controller: '/index.php/cms/model',U_controller: '/u.php/cms/model'},
			'statistic': {url: '/cms/modules/statistic',controller: '/index.php/cms/statistic',U_controller: '/u.php/cms/statistic'},
			'wechat': {url: '/cms/modules/wechat',controller: '/index.php/cms/wechat',U_controller: '/u.php/cms/wechat'}
		},
		core: {'': {url: '',controller: '/index.php'},
			'46': {url: '/modules/46',controller: '/index.php/46',U_controller: '/u.php/46'},
			'credit': {url: '/modules/credit',controller: '/index.php/credit',U_controller: '/u.php/credit'},
			'crontab': {url: '/modules/crontab',controller: '/index.php/crontab',U_controller: '/u.php/crontab'},
			'cservice': {url: '/modules/cservice',controller: '/index.php/cservice',U_controller: '/u.php/cservice'},
			'dbm': {url: '/modules/dbm',controller: '/index.php/dbm',U_controller: '/u.php/dbm'},
			'forms': {url: '/modules/forms',controller: '/index.php/forms',U_controller: '/u.php/forms'},
			'friendlink': {url: '/modules/friendlink',controller: '/index.php/friendlink',U_controller: '/u.php/friendlink'},
			'interview': {url: '/modules/interview',controller: '/index.php/interview',U_controller: '/u.php/interview'},
			'label': {url: '/modules/label',controller: '/index.php/label',U_controller: '/u.php/label'},
			'letter': {url: '/modules/letter',controller: '/index.php/letter',U_controller: '/u.php/letter'},
			'mail': {url: '/modules/mail',controller: '/index.php/mail',U_controller: '/u.php/mail'},
			'member': {url: '/modules/member',controller: '/index.php/member',U_controller: '/u.php/member'},
			'message': {url: '/modules/message',controller: '/index.php/message',U_controller: '/u.php/message'},
			'notify': {url: '/modules/notify',controller: '/index.php/notify',U_controller: '/u.php/notify'},
			'opinion': {url: '/modules/opinion',controller: '/index.php/opinion',U_controller: '/u.php/opinion'},
			'page': {url: '/modules/page',controller: '/index.php/page',U_controller: '/u.php/page'},
			'pay': {url: '/modules/pay',controller: '/index.php/pay',U_controller: '/u.php/pay'},
			'role': {url: '/modules/role',controller: '/index.php/role',U_controller: '/u.php/role'},
			'shortcutsms': {url: '/modules/shortcutsms',controller: '/index.php/shortcutsms',U_controller: '/u.php/shortcutsms'},
			'sms': {url: '/modules/sms',controller: '/index.php/sms',U_controller: '/u.php/sms'},
			'special': {url: '/modules/special',controller: '/index.php/special',U_controller: '/u.php/special'},
			'spider': {url: '/modules/spider',controller: '/index.php/spider',U_controller: '/u.php/spider'},
			'survey': {url: '/modules/survey',controller: '/index.php/survey',U_controller: '/u.php/survey'},
			'uploader': {url: '/modules/uploader',controller: '/index.php/uploader',U_controller: '/u.php/uploader'},
			'vote': {url: '/modules/vote',controller: '/index.php/vote',U_controller: '/u.php/vote'}
		}
	}
	};